modify build script for libraries & begin work on module loading

diff --git a/build b/build
--- a/build
+++ b/build
@@ -58,7 +58,6 @@ fi
 [ -e .ofiles ] && rm .ofiles
 [ -e .ofiles32 ] && rm .ofiles32
 
-
 OLDPATH=$PATH
 PATH=$CROSSPATH
 CC=$(command -v $TARGET-gcc)
@@ -71,10 +70,12 @@ fi
 PATH=$OLDPATH
 
 AS=$(command -v nasm)
+AR=$(command -v ar)
 
 [ -z "$CC" ] && { echo >&2 "$TARGET-gcc not found in cross-compiler path ($CROSSPATH)" ; exit 1 ; }
 [ -z "$CC32" ] && { echo >&2 "$TARGET32-gcc not found in cross-compiler path ($CROSSPATH)" ; exit 1 ; }
 [ -z "$AS" ] && { echo >&2 "nasm not found in path ($PATH)" ; exit 1 ; }
+[ -z "$AR" ] && { echo >&2 "ar not found in path ($PATH)" ; exit 1 ; }
 
 CFLAGS="-O$OLEVEL -std=gnu99 -Wall -Werror -ffreestanding -mcmodel=large -mno-red-zone -march=$ARCH -fno-unwind-tables"
 if [ "$EMU32" == "YES" ] ; then
@@ -90,8 +91,10 @@ else
     LDCFLAGS32="-O$OLEVEL -ffreestanding -nostdlib -lgcc -fno-exceptions"
 fi
 
-[ -z "$LINKER_SCRIPT" ] && { echo "Options error: LINKER_SCRIPT not specified" ; exit 1 ; }
-[ ! -e src/$LINKER_SCRIPT ] && { echo "Options error: $LINKER_SCRIPT not found" ; exit 1 ; }
+ARFLAGS="rcs"
+
+[ -z "$LINKER_SCRIPT" ] && { echo >&2 "Options error: LINKER_SCRIPT not specified" ; exit 1 ; }
+[ ! -e src/$LINKER_SCRIPT ] && { echo >&2 "Options error: $LINKER_SCRIPT not found" ; exit 1 ; }
 
 for M in $(echo $MODULES) ; do
     (
@@ -106,6 +109,7 @@ for M in $(echo $MODULES) ; do
         M32=$(grep -o ':m32:' <<< $FLAGS)
         CUSTOM_LS=$(grep -o ':cls:' <<< $FLAGS)
         PREP=$(grep -o ':prep:' <<< $FLAGS)
+        ISLIB=$(grep -o ':lib:' <<< $FLAGS)
         
         MNAME=$(sed 's/\//_/g' <<< $M)
 
@@ -116,13 +120,31 @@ for M in $(echo $MODULES) ; do
             [ -e src/shared/$F ] && cp src/shared/$F src/$M || { echo "Failed: shared file $F not found ($M)" >> src/$M/.error_log ; exit 1 ; }
         done
         
+        [ -e out/$M/.lfiles ] && rm out/$M/.lfiles
+        
+        touch out/$M/.lfiles
+        
+        for F in $LIBS ; do
+            [ ! -e out/libinfo ] && { echo "Failed: no libinfo in out/ ($M)" >> .error_log ; exit 1 ; }
+            LP=$(sed -n 's/^'$F' \([^ ]*\) .*$/\1/p' < out/libinfo)
+            LPNAME=$(sed -n 's/^'$F' [^ ]* \(.*\)$/\1/p' < out/libinfo)
+            [ -z "$LP" ] && { echo "Failed: library $F not found ($M)" >> src/$M/.error_log ; exit 1 ; }
+            cp $LP out/$M
+            echo "$LP" >> out/$M/.lfiles
+            [ ! -e src/$F/module-info ] && { echo "Failed: no module-info for library $F ($M)" >> .error_log ; exit 1 ; }
+            [ ! -e out/publicinfo ] && { echo "Failed: no publicinfo in out/ ($M)" >> .error_log ; exit 1 ; }
+            for PF in $(sed -n 's/^$F \(.*\)$/\1/p' < out/publicinfo) ; do
+                cp src/$F/$PF src/$M
+            done
+        done
+        
+        [ -e src/$M/.error_log ] && { cat src/$M/.error_log >> .error_log ; exit 1 ; }
+        
         for F in $(ls -R src/$M) ; do
             [ src/$M/$F -nt out/$M/m_$MNAME.bin ] && touch src/$M/.updated
         done
         
-        wait
-
-        [ -e src/$M/.error_log ] && { cat src/$M/.error_log >> .error_log ; exit 1 ; }
+#        wait
         
         [ ! -e src/$M/.updated ] && { [ -n "$VERBOSE" ] && echo "Skipping $M" ; true ; } && exit 0
         
@@ -193,9 +215,18 @@ for M in $(echo $MODULES) ; do
         
         [ -e src/$M/.error_log ] && cat src/$M/.error_log >> .error_log && exit 1
         
-        [ -n "$VERBOSE" ] && echo "Linking $M"
-        
-        $CC_ACTUAL -T $LSH -o out/$M/m_$MNAME.bin $LDCFLAGS_ACTUAL $(cat out/$M/.ofiles) || { echo "Failed: link ($M)" >> src/$M/.error_log ; exit 1 ; }
+        if [ -z "$ISLIB" ] ; then
+            [ -n "$VERBOSE" ] && echo "Linking $M"
+            
+            $CC_ACTUAL -T $LSH -o out/$M/m_$MNAME.bin $LDCFLAGS_ACTUAL $(cat out/$M/.ofiles) $(cat out/$M/.lfiles) || { echo "Failed: link ($M)" >> src/$M/.error_log ; exit 1 ; }
+        else
+            [ -n "$VERBOSE" ] && echo "Archiving $M"
+            
+            $AR $ARFLAGS out/$M/$MNAME.a $(cat out/$M/.ofiles) || { echo "Failed: archive ($M)" >> src/$M/.error_log ; exit 1 ; }
+            
+            echo "$M out/$M/$MNAME.a $MNAME.a" >> out/libinfo
+            echo "$M $PUBLIC" >> out/publicinfo
+        fi
         
         [ -e src/$M/.error_log ] && { cat src/$M/.error_log >> .error_log ; exit 1 ; }
         
@@ -204,6 +235,9 @@ for M in $(echo $MODULES) ; do
         [ -n "$VERBOSE" ] && echo "Finished $M (out/$M/m_$MNAME.bin)"
         
     )
+    
+    [ -e .error_log ] && break
+    
 done
 
 wait
